baseURL = 'https://leoelsolh.com/'
languageCode = 'en-us'
title = 'leoelsolh'
theme = 'PaperMod'

[params]
  defaultTheme = 'dark'
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  ShowPostNavLinks = true

[params.homeInfoParams]
  Title = "Programming&nbsp;· scripting&nbsp;· offensive&nbsp;security"

[params.assets]
  favicon = "falconhead.jpg"
  favicon16x16 = "falconhead.jpg"
  favicon32x32 = "falconhead.jpg"
  theme_color = "#0D1B2A"
  msapplication_TileColor = "#0D1B2A"

[[menu.main]]
  identifier = "github" 
  name = "Github" 
  url = "https://github.com/leoelsolh" 
  weight = 1
